### ISSUE TITLE
CPU flags vary between runs on Mac OS X

### ISSUE THREAD

**Issue by JiabinYang** [workhorsy/py-cpuinfo#133] opened 2019-06-26 09:16 UTC
CPU: Mac with intel i5 7265U
OS: MacOS 10.14
Python: python2/3.6/3.7
Version: latest

it seems the result is different when I call this func twice

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/22361972/60167615-00c3d200-9836-11e9-8a63-f75c02aa53a4.png">

**Comment by workhorsy** [comment] 2019-06-26 19:25
I'm working on a new branch that can trace exactly what is happening. That way we can see why it is returning different results.

**Comment by tensor-tang** [comment] 2019-06-27 12:25
I tried with tag 4.0.0 seems work fine.

**Comment by FabioLuporini** [comment] 2019-09-16 06:53
Reproduced on linux (ubuntu) too

**Comment by workhorsy** [comment] 2020-07-04 17:25
I finally got a chance to test this on OSX. It turns out OSX doesn't like allocating memory with valloc and modifying it with mprotect. It is preferred that people use mmap instead. So now we use mmap.

**Comment by workhorsy** [comment] 2020-07-04 17:30
Fixed in #151

**Closed by workhorsy** 2020-07-04 17:30 UTC
Labels: bug
